### ISSUE TITLE
Linux GOPATH 问题

### ISSUE THREAD

**Issue by hjsBack** [blockchain-desktop/hyperledger-fabric-desktop#140]
在安装链码时需要用到本地配置的GOPATH。
对于Linux来说，环境变量有多种配置方式，如~/.bashrc,  ~/.profile,  /etc/profile  
当把GOPATH配置在~/.bashrc中时，打包好的程序是读取不到的，需要配置在后两个（推荐第二个），最重要的一点是更改配置后需要重启系统才能使用，用source更新配置是不行的

**Comment by dengyi9** [comment]
类似问题，可参见 #16

**Comment by dengyi9** [comment]
暂时标记为wontfix。 考虑后期通过封装go语言到客户端，在客户端内维护GOPATH的方式，解决各平台GOPATH的问题

**Comment by dengyi9** [comment]
后续进展统一在#16讨论
