### ISSUE TITLE
通道功能页面，建议增加 

### ISSUE THREAD

**Issue by dengyi9** [blockchain-desktop/hyperledger-fabric-desktop#15]
页面主要功能：创建通道、查询现有通道

**Comment by dengyi9** [comment]
Done. See v0.2.0-beta

**Comment by liurain** [comment]
导入的configtx.yaml文件，在使用教程中并未提及联盟名称的配置，但是这个参数确实是会写入到通道配置里面的。一般默认情况是“SampleConsortium”但有时候可能不是，这种情况下创建通道就要指定对应的联盟

**Comment by dengyi9** [comment]
@liurain   谢谢。这个问题我们在 #222 跟进
