### ISSUE TITLE
`tls cert` is a little bit confusing

### ISSUE THREAD

**Issue by CsterKuroi** [blockchain-desktop/hyperledger-fabric-desktop#154]
These two items on the login page may need a better name. In fact, it's like `tlsCACerts` right now?

![20181226154245](https://user-images.githubusercontent.com/12230174/50437495-e8c1d300-0924-11e9-83ec-1542558ff272.png)

**Comment by CsterKuroi** [comment]
Reference:

https://github.com/hyperledger/blockchain-explorer/blob/master/app/platform/fabric/config.json#L60

https://github.com/IBM-Blockchain/marbles/blob/master/config/connection_profile_tls.json#L47

**Comment by hjsBack** [comment]
you can join our wechat group at your convenience.here is my QRcode
![default](https://user-images.githubusercontent.com/24680392/50439589-9507b780-092d-11e9-96cf-8e67828b8eb4.jpg)
