### ISSUE TITLE
chaincode invoke页面中chaincode应为文本框

### ISSUE THREAD

**Issue by IamChuancey** [blockchain-desktop/hyperledger-fabric-desktop#197]
链码这个输入框之前是和通道一样的选择框， 但是那个函数只有admin user才有权限查到 ，当普通user登入时是空的而且不可手动输入，如图 ，是否将其改成文本框 让普通user也可以手动输入，
![image](https://user-images.githubusercontent.com/29730996/54492123-c2497d80-48fe-11e9-9a91-26b70461d270.png)

**Comment by dengyi9** [comment]
#198   与这个issue是一件事，具体实现考虑统一在那讨论。暂时先关闭此问题。
