### ISSUE TITLE
普通user登入desktop时总是报错权限问题

### ISSUE THREAD

**Issue by IamChuancey** [blockchain-desktop/hyperledger-fabric-desktop#198]
admin user 登入时无任何问题，普通user登入时总会出现如下图所示错误，见右下角错误提示
![image](https://user-images.githubusercontent.com/29730996/54492564-b495f700-4902-11e9-99fd-f5b1f176760f.png)

**Comment by dengyi9** [comment]
经过我再次确认，确实存在此问题。在链码调用、链码安装 功能页都存在。 

具体修改，改为文本框是一个思路，让普通用户手动填写。 参见#197。
考虑进一步调研是否能通过证书直接判断用户是否admin, 从而区别处理。 若不能，则需考虑如何一套逻辑兼容两种情况，或实在不行，则直接降级回到手动填写的方式。 

**Comment by dengyi9** [comment]
考虑使用User.getRoles()方法获取证书中附带的角色信息，但目前sdk未实现对证书角色信息的解析。因此目前结论为无法直接获取用户角色是否为admin。

目前问题为，普通用户因无法获取通道信息而导致页面报错，需通过其他方式绕过。

**Comment by dengyi9** [comment]
版本情况：
在fabric-client:v1.3版本下可正常运行。

**Comment by dengyi9** [comment]
再次确认，v1.3版本下正常。 或问题在于版本冲突导致，暂不处理。

复现：
1. package.json 中确认版本  "fabric-client": "~1.3.0"
2. 启动fabric/v1.3/first-network网络, `./byfn.sh up`
3. 修改fabric/v1.3/first-network中的desktopConfig.yaml，确认使用user私钥证书。 
4. 使用desktopConfig.yaml文件登陆
