### ISSUE TITLE
可以增加查看节点和组织信息的功能吗

### ISSUE THREAD

**Issue by youqianyi** [blockchain-desktop/hyperledger-fabric-desktop#227]
因为同一个通道的成员信息应该共享吧，我作为一个用户应该知道我的channel有几个成员，在这里也提一个额外的建议，我觉得既然用了node，可以考虑也实现web形式(应该有很多用户会有这个需求)，谢谢。

**Comment by dengyi9** [comment]
谢谢你的建议，查看节点和组织信息是个好需求。 我们之前也思考过，但node sdk好像没有提供很好的接口封装。 可能解析通道配置是一个办法， 但具体还需要有人调研。  至于web形式，也有考虑。

建议在 #170, #192 集中讨论。本issue先关闭了
