### ISSUE TITLE
链码安装和实例化

### ISSUE THREAD

**Issue by zhaoyulong1** [blockchain-desktop/hyperledger-fabric-desktop#231]
我在远程linux服务器启动了fabcar网络，v1.3.0
在windows上安装最新版应用，查询和执行链码都没问题
但是在安装链码和实例化链码时没有成功。
我做了以下尝试：
  1.把链码地址写成服务器中链码的位置，实际位置在服务器的/fabric-samples/chaincode/fabcar/go，在桌面应用写 github.com/fabcar/go
  2.又试了/opt/gopath/src/github.com/fabcar/go
  3.在windows安装了go，配置了gopath，在 D:\Go\src\chaincode 中放入链码，在桌面应用填chaincode
  4.在服务器使用cli，安装和实例化没有问题，且桌面应用可以看到新链码
结果都直接返回错误，但并未提示什么错误。是我哪里操作有问题吗？

**Comment by zhaoyulong1** [comment]
把链码放到 服务器的gopath的src中也试过了，也不行

**Comment by zhaoyulong1** [comment]
证书用的Admin

**Comment by zhaoyulong1** [comment]
是否少了 -l 选项？

**Comment by dengyi9** [comment]
请参考用户文档 

`
注： fabric默认在GOPATH路径下src文件夹下寻找链码文件，路径只需具体到链码文件的所在文件夹，您可参考下面的例子： 如：要安装的链码文件的完整路径为：/Users/my/go/src/chaincode/fabcar/go/fabcar.go GOPATH为前半部分/Users/my/go/，则需填入的路径为：chaincode/fabcar/go
`

**Comment by dengyi9** [comment]
链码文件应是放在客户端的机器中

**Comment by zhaoyulong1** [comment]
我是按照用户文档操作的，将链码放到了客户端机器中，正如您回复的那样做的，但是直接返回错误，不知道哪里出现问题了？

**Comment by zhaoyulong1** [comment]
我还给客户端机器gopath中的src中放入了fabric源码，按照路径。

**Comment by zhaoyulong1** [comment]
难道是客户端也需要配置fabric的环境？

**Comment by zhaoyulong1** [comment]
![image](https://user-images.githubusercontent.com/13092764/69004787-c0373300-0953-11ea-9c92-751d6a8a1e9a.png) 
![image](https://user-images.githubusercontent.com/13092764/69004795-cf1de580-0953-11ea-9db5-b1ebe571e71c.png)
![image](https://user-images.githubusercontent.com/13092764/69004804-e957c380-0953-11ea-95b0-5ed3b4dbbebf.png)
![image](https://user-images.githubusercontent.com/13092764/69004808-f2e12b80-0953-11ea-866d-1988a8d21e4d.png)

**Comment by zhaoyulong1** [comment]
我用的1.3.0版本的，我在命令行中需要指定链码语言才能安装链码，但是这里没有这个标签填写，是否是这个问题？   还是我客户端配置有问题？

**Comment by dengyi9** [comment]
我暂时看不出来，客户端不需要配置fabric的东西。可以试试修改下链码名称、版本号、通道。

1. 目前只测试了go链码安装，所以无需制定，默认是Go的链码
2. 你可以看看 c盘内的日志是否有有用信息。  大概路径是`c:\Users\你的用户\Fabric-Desktop\`

**Comment by zhaoyulong1** [comment]
谢谢您的回复，我怀疑是环境变量的问题，我重启了客户端，现在好了。  但是之前有个怪异的现象就是我网络重开了下，但是桌面应用一点开还是保存和显示的以前使用的信息，但是还能查询链码执行链码。应该是您使用了本地数据库保存了对吧，我看源码是这样的。  这个算bug吗？
